spring:
  profiles.active: local
management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'